"""Multi-Agent Orchestrator for ClausaFractalAI.

Coordinates parallel and sequential agent workflows across Router, Legal QA Analyst,
Critic Reflection, Blindspot Detector, Policy Collider, and Copilot Action Agents.
Provides both full batch responses and Server-Sent Events (SSE) streaming.
"""

import json
from typing import AsyncIterator, List, Optional

from pydantic import BaseModel, Field

from agents.blindspot import BlindspotDetectorAgent, BlindspotReport
from agents.copilot_actions import (
    ActionableCopilotAgent,
    AttorneyPrepSheet,
    CounterClauseProposal,
)
from agents.critic_reflection import CriticReflectionAgent
from agents.policy_collider import PolicyColliderAgent, PolicyCollisionReport
from agents.qa_analyst import LegalQAAnalystAgent
from agents.router import RouterAgent
from agents.verification_guard import Citation
from services.rag_engine import RAGEngine


class OrchestratedResponse(BaseModel):
    """Consolidated typed result generated by the multi-agent orchestration pipeline.

    Attributes:
        intent: Classified legal workflow intent.
        answer: Synthesized and verified legal guidance.
        citations: Grounded bidirectional citation records.
        quality_score: Faithfulness score from critic reflection.
        reflections: Self-improving critique notes and repair traces.
        blindspot_report: Optional omitted clause audit report.
        collision_report: Optional version diff and impact matrix report.
        attorney_prep_sheet: Optional executive attorney consultation checklist.
        counter_clause: Optional negotiated counter-proposal language.
    """

    intent: str
    answer: str
    citations: List[Citation] = Field(default_factory=list)
    quality_score: float = 10.0
    reflections: List[str] = Field(default_factory=list)
    blindspot_report: Optional[BlindspotReport] = None
    collision_report: Optional[PolicyCollisionReport] = None
    attorney_prep_sheet: Optional[AttorneyPrepSheet] = None
    counter_clause: Optional[CounterClauseProposal] = None


class LegalOrchestrator:
    """Master multi-agent orchestrator managing agent graphs and streaming execution."""

    def __init__(
        self,
        rag_engine: Optional[RAGEngine] = None,
        router_agent: Optional[RouterAgent] = None,
        qa_agent: Optional[LegalQAAnalystAgent] = None,
        critic_agent: Optional[CriticReflectionAgent] = None,
        blindspot_agent: Optional[BlindspotDetectorAgent] = None,
        collider_agent: Optional[PolicyColliderAgent] = None,
        copilot_agent: Optional[ActionableCopilotAgent] = None,
    ) -> None:
        """Initialize orchestrator dependencies and sub-agents.

        Args:
            rag_engine: Semantic vector search and triple store engine.
            router_agent: Intent classification agent.
            qa_agent: Deep legal question answering agent.
            critic_agent: Self-improving reflection critic agent.
            blindspot_agent: Omission and contract risk auditor agent.
            collider_agent: Contract version comparison agent.
            copilot_agent: Actionable deliverables generator agent.
        """
        self.rag_engine = rag_engine or RAGEngine()
        self.router_agent = router_agent or RouterAgent()
        self.qa_agent = qa_agent or LegalQAAnalystAgent(rag_engine=self.rag_engine)
        self.critic_agent = critic_agent or CriticReflectionAgent()
        self.blindspot_agent = blindspot_agent or BlindspotDetectorAgent()
        self.collider_agent = collider_agent or PolicyColliderAgent()
        self.copilot_agent = copilot_agent or ActionableCopilotAgent()

    def process_query(
        self,
        query: str,
        document_id: str = "doc_default",
        document_text: str = "",
        comparison_text: str = "",
        complexity_level: str = "STANDARD",
        forced_intent: Optional[str] = None,
    ) -> OrchestratedResponse:
        """Execute the coordinated multi-agent workflow for a user query.

        Args:
            query: User's legal inquiry or negotiation task.
            document_id: Primary document identifier.
            document_text: Raw text of the active document.
            comparison_text: Optional comparison text for policy diffing.
            complexity_level: Tone and detail modulation ('ELI5', 'STANDARD', etc.).
            forced_intent: Optional override for deterministic routing.

        Returns:
            OrchestratedResponse containing consolidated outputs from active agents.
        """
        # Step 1: Routing & Intent Classification
        if forced_intent:
            intent = forced_intent
        else:
            route_res = self.router_agent.classify(query=query)
            intent = route_res.intent

        # Step 2: Route-specific Execution Graph
        if intent == "BLINDSPOT_AUDIT":
            # Extract document text from RAG chunks if empty
            if not document_text:
                chunks = self.rag_engine.get_document_chunks(document_id)
                document_text = " ".join(c.text for c in chunks)

            report = self.blindspot_agent.audit(
                document_text=document_text,
                document_id=document_id,
            )
            summary = (
                f"Blindspot Audit completed: {len(report.omitted_findings)} omissions identified. "
                f"Compliance Score: {report.compliance_score:.1f}%."
            )
            return OrchestratedResponse(
                intent="BLINDSPOT_AUDIT",
                answer=summary,
                blindspot_report=report,
            )

        if intent == "POLICY_DIFF":
            if not document_text:
                chunks_a = self.rag_engine.get_document_chunks(document_id)
                document_text = " ".join(c.text for c in chunks_a)

            collision = self.collider_agent.compare(
                doc_a_text=document_text,
                doc_b_text=comparison_text,
                doc_a_id=document_id,
                doc_b_id="comparison_v2",
            )
            return OrchestratedResponse(
                intent="POLICY_DIFF",
                answer=collision.overall_verdict,
                collision_report=collision,
            )

        if intent == "ATTORNEY_PREP":
            prep = self.copilot_agent.generate_attorney_prep_sheet(document_id=document_id)
            return OrchestratedResponse(
                intent="ATTORNEY_PREP",
                answer=prep.executive_summary,
                attorney_prep_sheet=prep,
            )

        if intent == "CLAUSE_REWRITE":
            proposal = self.copilot_agent.rewrite_clause(clause_text=query)
            return OrchestratedResponse(
                intent="CLAUSE_REWRITE",
                answer=proposal.counter_clause,
                counter_clause=proposal,
            )

        # Default: LEGAL_QA with Self-Improving Critic Reflection
        qa_result = self.qa_agent.answer_query(
            query=query,
            complexity_level=complexity_level,
        )

        critic_result = self.critic_agent.review(
            query=query,
            answer=qa_result.answer,
            citations=qa_result.citations,
            retrieved_chunks=qa_result.retrieved_chunks,
        )

        return OrchestratedResponse(
            intent="LEGAL_QA",
            answer=critic_result.improved_answer,
            citations=critic_result.verified_citations,
            quality_score=critic_result.fidelity_score,
            reflections=critic_result.critique_notes,
        )

    async def stream_chat(
        self,
        query: str,
        document_id: str = "doc_default",
        document_text: str = "",
        complexity_level: str = "STANDARD",
    ) -> AsyncIterator[str]:
        r"""Stream real-time tokens and citations via Server-Sent Events (SSE).

        Args:
            query: User's legal inquiry.
            document_id: Target document identifier.
            document_text: Optional document text override.
            complexity_level: Audience tone slider value.

        Yields:
            Formatted SSE chunks ('event: ...\ndata: ...\n\n').
        """
        # Execute workflow
        res = self.process_query(
            query=query,
            document_id=document_id,
            document_text=document_text,
            complexity_level=complexity_level,
        )

        # 1. Intent Event
        yield f"event: intent\ndata: {json.dumps({'intent': res.intent})}\n\n"

        # 2. Token Stream (chunked word tokens for smooth SSE visualization)
        words = res.answer.split(" ")
        for i, word in enumerate(words):
            token = word + (" " if i < len(words) - 1 else "")
            token_payload = json.dumps({"token": token})
            yield f"event: token\ndata: {token_payload}\n\n"

        # 3. Citations Event
        citations_data = [c.model_dump() for c in res.citations]
        yield f"event: citation\ndata: {json.dumps(citations_data)}\n\n"

        # 4. Completion Event
        done_payload = json.dumps(
            {
                "status": "completed",
                "quality_score": res.quality_score,
                "reflections": res.reflections,
                "has_blindspots": res.blindspot_report is not None,
                "has_diff": res.collision_report is not None,
                "has_prep": res.attorney_prep_sheet is not None,
                "has_counter": res.counter_clause is not None,
            }
        )
        yield f"event: done\ndata: {done_payload}\n\n"
