"""Pydantic V2 immutable data contracts for Neuro-Symbolic Agent Mesh.

All inter-agent messages and solver inputs/outputs are strictly typed, validated,
and frozen to prevent accidental state mutation across agent boundaries.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class RiskSeverity(str, Enum):
    """Categorical severity levels for legal and operational risks."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ContractClause(BaseModel):
    """Immutable model representing an analyzed legal contract clause."""

    model_config = ConfigDict(frozen=True)

    clause_id: str
    title: str
    text: str
    page: int = 1
    liability_cap_usd: Optional[float] = None
    notice_days: Optional[int] = None
    is_mutual_indemnity: bool = False
    has_consequential_damages_waiver: bool = False
    governing_law: Optional[str] = None
    risk_level: RiskSeverity = RiskSeverity.LOW


class ActionPlan(BaseModel):
    """Proposed action plan generated by System 1 Neural Perception."""

    model_config = ConfigDict(frozen=True)

    plan_id: str
    intent: str
    proposed_action: str
    risk_category: str
    target_clauses: List[ContractClause] = Field(default_factory=list)
    proposed_liability_cap_usd: Optional[float] = None
    proposed_notice_days: Optional[int] = None
    require_mutual_indemnity: bool = True
    forbid_consequential_waiver: bool = True
    confidence: float = Field(ge=0.0, le=1.0, default=0.95)
    repair_attempt: int = 0


class VerificationResult(BaseModel):
    """Formal mathematical verification result from System 2 Symbolic Solver."""

    model_config = ConfigDict(frozen=True)

    is_satisfiable: bool
    status: str  # "SAT", "UNSAT", "UNKNOWN"
    unsat_core: List[str] = Field(default_factory=list)
    model_assignments: Dict[str, Any] = Field(default_factory=dict)
    diagnostics: str = ""
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class AgentTraceEvent(BaseModel):
    """Immutable event representing an Agent-to-Agent (A2A) delegation hop."""

    model_config = ConfigDict(frozen=True)

    trace_id: str
    source_agent: str
    target_agent: str
    hop_count: int
    intent: str
    payload_hash: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class HITLCheckpoint(BaseModel):
    """Execution state checkpointed to Redis for Human-in-the-Loop review."""

    model_config = ConfigDict(frozen=True)

    checkpoint_id: str
    trace_id: str
    plan: ActionPlan
    unsat_reasons: List[str]
    resumption_token: str
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    status: str = "PENDING_REVIEW"
